name = input("user name: ")
surname = input("user surname: ")
age = input("user age: ")
birth = input("birthday : ")
print("======================")
print("name:", name)
print("surname:", surname)
print("age:", age)
print("birth:", birth)
print("======================")